### ISSUE TITLE
US003 - Atuar como Tracker

### ISSUE THREAD

**Issue by tallysmartins** [joaaogui/pesquini#14]
**Como** Gerente
**Eu desejo** efetuar o papel de Tracker da Sprint 1
**Para que** eu possa acompanhar o andamento do projeto

Responsáveis: Alex

Task List
- [x] Atualizar Wiki
- [x] Atualizar Quadro de Pareamento
- [x] Atualizar Kanban físico
- [x] Atualizar quadro de presença
